### ISSUE TITLE
repeat-until with check before first iteration?

### ISSUE THREAD

**Issue by mal-tee** [ShiftLeftSecurity/overflowdb#225]
Hi!

If I understand #145 correctly, the `repeat-until` pattern always executes the step once. Is there an elegant way to change that behaviour such that the condition is checked first?

And I am not sure if I missed sth. in the documentation, but a small hint about the current behaviour would be useful.

**Comment by mpollmeier** [comment]
Your understanding is correct. IIRC the main thing that made us drop while/repeat semantics is that we didn't find a nice way to express it in the DSL. Looking back at it now, I guess repeat/while is the best option, but `while` is a scala keyword and therefor would needed to be quoted. How about this:
```
trav.repeat(_.out)(_.until(_.hasLabel("FOO"))   // only checks after the first iteration - as before
trav.repeat(_.out)(_.`while`(_.hasLabel("FOO"))  // also checks at the first iteration
trav.repeat(_.out)(_.whilst(_.hasLabel("FOO"))    // same as above, simply given it a different/alternatiuve name to avoid quoting
```

**Comment by mal-tee** [comment]
Thank you for the info! Avoiding quotes sounds good.

**Comment by mpollmeier** [comment]
Thanks for bringing this up, it makes sense to add and doesn't look too hard. I'll take a look in the next few days.

**Comment by mpollmeier** [comment]
implemented in https://github.com/ShiftLeftSecurity/overflowdb/pull/227

**Comment by mpollmeier** [comment]
@mal-tee looks good to you?

**Comment by mal-tee** [comment]
I'm in no position to judge the implementation, but the usage in the tests looks good to me! Thanks!
