### ISSUE TITLE
Support for GraphSON 3.0 Export Format

### ISSUE THREAD

**Issue by DavidBakerEffendi** [ShiftLeftSecurity/overflowdb#325]
I've received requests for `joern-export` to support a JSON export format. Following GraphML I suggest supporting the [GraphSON 3.0 spec](https://tinkerpop.apache.org/docs/3.4.1/dev/io/#graphson-3d0) would be a good baseline for a formal graph JSON format.

I'm happy to drive this feature and get support for this out soon.

**Comment by mpollmeier** [comment]
Sounds great, adding some json format was on my list for some time as well.
How about you give it a shot and pull me in for help? Just hit me up on discord.
